# Generated by Django 5.0.6 on 2024-10-04 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.IntegerField(choices=[(1, 'Annual Leave'), (2, 'Sick Leave'), (3, 'R1 Leave'), (4, 'R2 Leave')], verbose_name='Leave Type')),
                ('comment', models.CharField(blank=True, default='', max_length=50, verbose_name='Comment')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('balance', models.PositiveIntegerField(verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'permissions': (('Balance', 'balance - create leave balance'),),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Canceled'), (5, 'Modified')], default=1, verbose_name='Request Status')),
                ('approval_stage', models.IntegerField(choices=[(1, 'Officer'), (2, 'Manager')], default=1, verbose_name='Approval Stage')),
                ('leave_type', models.IntegerField(choices=[(1, 'Annual Leave'), (2, 'Sick Leave'), (3, 'R1 Leave'), (4, 'R2 Leave')], verbose_name='Leave Type')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('days', models.PositiveIntegerField(verbose_name='Days')),
                ('comment', models.CharField(blank=True, default='', max_length=50, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('leave_balance_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.leavebalance', verbose_name='Leave Balance Number')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_reguest_officer', to=settings.AUTH_USER_MODEL, verbose_name='Officer')),
                ('original_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.leaverequest', verbose_name='original request')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'permissions': (('HR', 'hr - view leaves'),),
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected')], verbose_name='Approval status')),
                ('stage', models.IntegerField(choices=[(1, 'Officer'), (2, 'Manager')], verbose_name='stage')),
                ('comment', models.CharField(blank=True, default='', max_length=50, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leaverequest', verbose_name='Leave Request Id')),
            ],
            options={
                'verbose_name': 'Leave Approval',
                'verbose_name_plural': 'Leave Approvals',
                'permissions': (('Officer', 'officer - approve stage 1 request'), ('Manager', 'manager - approve stage 2 request')),
            },
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'end_date'), name='unique_leavebalance'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'from_date', 'to_date', 'officer'), name='unique_leaverequest'),
        ),
    ]
